export const Todoli = [
    {
        linkUrl:'https://treefonts.com/',
        name:'待付款訂單'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'待出貨訂單'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'已出貨訂單'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'待退貨/退款訂單'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'待取消訂單'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'未通過商品'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'已售完商品'
    },
    {
        linkUrl:'https://treefonts.com/',
        name:'待確認活動'
    },
];